name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: ${{ runner.os }}-venv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir .venv
        pip install pipenv
        pipenv sync --bare -d
    - name: Run Tests
      run: |
        python manage.py test
